apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-notify
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: postsync-container
        image: curlimages/curl
        command: ["sh", "-c", "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Deployment completed successfully!\"}' https://hooks.slack.com/services/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"]
      restartPolicy: Never