apiVersion: batch/v1
kind: Job
metadata:
  name: syncfail-alert
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
      - name: syncfail-container
        image: busybox
        command: ["sh", "-c", "echo 'SyncFail: Deployment failed!'"]
      restartPolicy: Never