apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  annotations:
    link.argocd.argoproj.io/external-link: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httbin
      containers:
      - image: docker.io/mccutchen/go-httpbin:v2.15.0
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 8080