apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps-binding
  namespace: httpbin
subjects:
  - kind: ServiceAccount
    name: httpbin
    namespace: httpbin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-configmaps